### ISSUE TITLE
[Documentation] pdf and markdown documentation

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#1]
Not all of our Roku developers have Microsoft Office, so it would be great if the documentation was available as .pdf in addition to .docx

**Comment by EnTerr** [comment]
Not PDF even - since it's on github, best to be markdown, just like the readme.md. But yes, .docx bests .pdf in weird factor

**Comment by siekermantechnology** [comment]
Agreed, markdown would be even better if it's intended to stay on github.

**Comment by RokuRnD** [comment]
added markdown documentation: [unit-test-framework.md](https://github.com/rokudev/unit-testing-framework/blob/master/docs/unit-test-framework.md)
