### ISSUE TITLE
[Documentation] Add explanation of Setup() and TearDown()

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#10]
The Run() (or TestRunner__Run() function in fw_testRunner.brs has support for a SetUp() and TearDown(). It would be good if explanation of that is added to the documentation.

**Comment by RokuRnD** [comment]
@siekermantechnology thanks for the request. Done in https://github.com/rokudev/unit-testing-framework/releases/tag/v.1.3.0
