### ISSUE TITLE
SceneGraph support

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#11]
Is there any way to test SceneGraph code in the pkg:/components/ folder? The framework in its current state appears to depend on the "include all functions in all files in the same scope" characteristic of the /source/ folder. 

It also looks like it is built to mainly deal with BrightScript, not SceneGraph, although there are some custom ContentNode assertions in Test__API in the SlindingPanelsExample.

Expanding the use of the framework to include real SceneGraph support would be a good next step in its evolution, making it a stronger tool.

**Comment by EnTerr** [comment]
perhaps you can do that manually by overriding the `testsDirectory` (defaults to "pkg:/source/tests") of one Test Runner?

It is weird they did not give much thought to RSG though

**Comment by RokuRnD** [comment]
@siekermantechnology @EnTerr RSG support was added in version 1.2.1. Please check out the documentation and channel sample for more. We would appreciate your feedback!
