### ISSUE TITLE
Allow access to test results

### ISSUE THREAD

**Issue by BentOnCoding** [rokudev/unit-testing-framework#20]
I would like to put my application on a build server. At the moment there is no obvious way to get the results of a test session. 

Currently to execute your tests you need to run this command : 

`curl -d '' 'http://{ROKU_ADDRESS}:8060/launch/dev?RunTests=true'`

It would be nice if this call returned the results of your tests. 

Alternatively there could be another web api endpoint that would return the last set of tests results. 

A simple pass/fail response would get things moving quickly. 
It would be even better if the test results came back in some kind of parsable format.

**Comment by RokuRnD** [comment]
Hi @BentOnCoding , thanks for ypur request, but currently it is not possible to return tests output outside `Roku box` from `launch/AppID` endpoint.
To save your test results to external server you should overwrite `SendToServer` and `PrintStatistic` functions in `Logger object` or overwrite the `Logger object` with your own:

```
Runner = TestRunner()
Runner.logger.SetServerURL("Your server URL")
Runner.logger.SendToServer = YourCustomSendToServerFunction
Runner.logger.PrintStatistic = YourCustomPrintStatisticFunction
Runner.logger.SetEcho(true)
Runner.SetFailFast(true)
Runner.Run()
```

OR

```
Runner = TestRunner()
Runner.logger = YourLoggerCreationFunction()
Runner.SetFailFast(true)
Runner.Run()

```
