### ISSUE TITLE
[Feature request] Easy way to skip or run specific tests

### ISSUE THREAD

**Issue by eddiemf** [rokudev/unit-testing-framework#28]
I'm afraid there is no current implementation to easily skip or run specific test cases in this framework, right? Something like in javascript test frameworks where you simply add a `it.skip(...)` or `it.only(...)` so you can easily skip some test you don't want to be run or execute only one specific test (really useful when running all tests gets slow or when debugging a test).

The framework works very awesomely, thanks for that!

**Comment by RokuDevTools** [comment]
@eddiemf added @Skip annotation as well as filtering options via test run. Please see new v.2.1.0 (samples and documentation)

- https://github.com/rokudev/unit-testing-framework/tree/master/samples/SimpleTestApp_Annotation
- https://github.com/rokudev/unit-testing-framework/tree/master/samples/SimpleTestApp_SelectiveRuns
