### ISSUE TITLE
Triggering button press on RSG testing

### ISSUE THREAD

**Issue by eddiemf** [rokudev/unit-testing-framework#29]
Hello everyone, I'm currently trying to test a component and I can't find any way to trigger a button press (observing `buttonSelected` field). I can easily trigger key presses that I'm listening in the component by calling `onKeyEvent` but I can't do it on native components like `Button`. Of course I don't want to call directly the callback function as I'm trying to keep tests from knowing implementation details of the component, but that looks like the only way of doing it now.

Is there any preferred approach for this situation? 

Thanks in advance!

**Comment by lkrocek** [comment]
You can always use [External Control API](https://sdkdocs.roku.com/display/sdkdoc/External+Control+API) but this is not a part of unit tests to simulate user input, you should call function ahead, or if you want rather test a user interface is an [integration testing](https://en.wikipedia.org/wiki/Integration_testing) or [automated e2e](https://suite.st/)

**Comment by RokuDevTools** [comment]
not unit test functionality. @lkrocek has a good point and shared good links.
