### ISSUE TITLE
Exception when testStatObj is uninitialized

### ISSUE THREAD

**Issue by ronenbit1** [rokudev/unit-testing-framework#30]
Current Function:
Thread selected:  1*   1532:  
1533:          m.logger.AppendSuiteStatistic(totalStatObj, suiteStatObj)
1534:  
1535:          if TF_Utils__IsFunction(testSuite.TearDown)
1536:  ...amework/UnitTestFramework.brs(1540)              m.logger.PrintSuiteTeiafr Dtoewsnt(SttaesttOSbju.itRee.Nsaulmte) 
= 
"Fail" and m.failFast
1537:              testSuite.TearDown()
1538:          end if
1539:  
1540:*         if testStatObj.Result = "Fail" and m.failFast
1541:              exit for
1542:          end if
1543:      end for
1544:  
'Dot' Operator attempted with invalid BrightScript Component or interface reference. (runtime error &hec) in pkg:/source/testFramework/UnitTestFramework.brs(1540)
1540:         if testStatObj.Result = "Fail" and m.failFast

The code should add : 
if testStatObj = "uninitialized" ...

**Comment by RokuDevTools** [comment]
@ronenbit1 @catalin-ursachi thanks for the help. fixed.
