### ISSUE TITLE
assertEqual can no longer be used with strings

### ISSUE THREAD

**Issue by dparkerfmts** [rokudev/unit-testing-framework#35]
Due to this change https://github.com/rokudev/unit-testing-framework/commit/c65ced2409188d87dc80a584a599bbffc1503283#diff-b7ee3a6f6cb8a7d1221bdd4caf060989R2666 we can no longer use `assertEqual` to compare strings.
Because both input values are now converted to objects via the `box()` method we can no longer run comparison of strings. 

We are now reduced to using `assertTrue` and passing a comparator, e.g. `assertTrue("string" = "string")`  
This feels like a step backwards.

**Comment by dparkerfmts** [comment]
Ignore me. There seems to be some weird type issues going on unrelated to the testing framework.

**Comment by dparkerfmts** [comment]
So I think it would be beneficial to allow comparison between `String` and `roString`.

```
strObj = CreateObject("roString")
strObj.SetString("01:46:40")
expected = strObj.GetString()

return m.assertEqual("01:46:40", expected) // Fail
```

I don't think it's right that this fails due to the type conversion and resulting mismatch caused by the call to `box()`.

**Comment by lkrocek** [comment]
box is not event working every time:
`print type(box(box("a")+box("b"))) ' displays String not a roString`

**Comment by lkrocek** [comment]
PR https://github.com/rokudev/unit-testing-framework/pull/33 should fix it, merge it please!

**Comment by RokuDevTools** [comment]
@dparkerfmts @lkrocek fixed by @pawelhertman . merged to v.2.1.0
