### ISSUE TITLE
[Documentation] Add curl command to Usage section of documentation

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#5]
/tests/sample/SlidingPanelsExample/README.TXT contains the following curl command:

`$ curl -d '' 'http://{Roku Device IP Address:8060/launch/dev?RunTests=true'`

Might be good to add that to the Usage section of the documentation where it states that you need to do an HTTP POST, but doesn't explain which curl command to use to do that.

**Comment by EnTerr** [comment]
That's already covered in ECP docs, no?
https://sdkdocs.roku.com/display/sdkdoc/External+Control+Guide#ExternalControlGuide-launch/appID

In particular is not a magic quality of the framework but just some parameter which the example app you quote chooses to use. (I haven't looked at the source of that but in general i will be wary of baking such functionality in production channel - or at least i'll add check if channelID = "dev " first)

**Comment by RokuRnD** [comment]
@siekermantechnology thanks for the request, done in: https://github.com/rokudev/unit-testing-framework/releases/tag/v.1.3.0
