### ISSUE TITLE
[Suggestion] Add version number to framework files

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#6]
It would be great to get a version number in the framework files, so that once it is updated later on, we can easily see which version is in our existing projects and if we should update.

**Comment by RokuRnD** [comment]
Thank you for the suggestion, metadata part was added to the top of fw file. Example:
'*****************************************************************
'* Build Version: 1.1.0
'* Build Date: 1/20/2017
'*****************************************************************

Also, on GitHub, we would be adding new major/minor releases to the special section:

[https://github.com/rokudev/unit-testing-framework/releases](https://github.com/rokudev/unit-testing-framework/releases)
