### ISSUE TITLE
[Bug] FW_ArrayContains missing

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#7]
Several functions in fw_baseTestSuite.brs make use of the function FW_ArrayContains, but that appears to be missing. I assume there is another support file similar to fw_types.brs and fw_strings.brs which contains that function. If so, please add that.

**Comment by EnTerr** [comment]
<rolls eyes>

**Comment by samdozor** [comment]
This is a duplicate of https://github.com/rokudev/unit-testing-framework/issues/2, addressed by https://github.com/rokudev/unit-testing-framework/pull/12

**Comment by RokuRnD** [comment]
Thank you for filing the issue. New 1.1.0 version contains all the fixes.
