### ISSUE TITLE
[Suggestion] Additional log level which only logs failed test cases

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#8]
It would be useful to add a log level which only shows the failed tests in detail. That way the log clutter is minimal when no problems occur, but show sufficient detail when an assertion fails, without constantly having to change Runner.logger.SetVerbosity().

**Comment by RokuRnD** [comment]
@siekermantechnology thank you for your suggestion. This functionality was added in v.1.2.1.
