### ISSUE TITLE
[Suggestion] Log error when addTest fails

### ISSUE THREAD

**Issue by siekermantechnology** [rokudev/unit-testing-framework#9]
When building a test suite file and writing/adding various test cases, as soon as one of the function names that is added through this.addTest() is wrong, instead of showing an error in the log, none of the tests are executed anymore. Tracking down where the typo is, is now tricky, because the log gives no information which could help.

**Comment by EnTerr** [comment]
And "here is your problem": https://github.com/rokudev/unit-testing-framework/blob/28d8154fa688cd5683035528ff014e005d2124eb/fw_testRunner.brs#L208

`                    functionName = testSuiteRegex.Match(line).Peek()
                    eval("testSuite=" + functionName + "()")
`
Respectfully WTF @RokuDev? You eval() something and never bother to test if there was an error? ... in a test suite library??

**Comment by RokuRnD** [comment]
@siekermantechnology  eval() is now used only for getting function reference. Please take a look at new version v.1.2.1 and tell us if it fits your current needs.
